# This is the tmplgen data file
# See more about TOML files here:
#
#     * https://github.com/toml-lang/toml
#     * https://goo.gl/CEGc3C

[[Layouts]]
# This is the default layout
path = "/"
Filename = "main.html"



# Usage:
#
# {{ .String.Title }}     =>     Functionbox
#
# key/value added under [String] is accessible inside
# your HTML templates.
#
# Add your own string values here:
[String]
Title = "Functionbox"
Title_Index = "Home | Functionbox"
Title_SayHello = "Say Hello | Functionbox"
Title_404 = "Page Not Found | Functionbox"
Meta_Description = "Functionbox - creates your future function by function"



# Usage:
#
# <ul>
# {{- range .Array.Users }}
#    <li>
#        {{ .FirstName }}
#        {{ .LastName }}
#        {{ .Email }}
#    </li>
# {{- end }}
# </ul>
# Add your own Data arrays here:
[[Array.Header]]
    Name = "Firestatic Base Project"
    URL = "/"

[[Array.Header]]
    Name = "Contact"
    URL = "/contact"

[[Array.Footer]]
    Name = "Provider"
    URL = "/"
