# This is the tmplgen data file
# See more about TOML files here:
#
#     * https://github.com/toml-lang/toml
#     * https://goo.gl/CEGc3C

[[Layouts]]
# This it the default layout
path = "/"
Filename = "main.html"

[[Layouts]]
# This layout is used for 404.html page
path = "/404.html"
Filename = "error.html"


# Usage:
#
# {{ .String.Title }}     =>     Firestatic Base Project
#
# key/value added under [String] is accessible inside
# your HTML templates.
#
# Add your own string values here:
[String]
Title = "Provider"
Title_Index = "Provider"
Title_404 = "Page Not Found | Provider"



# Usage:
#
# <ul>
# {{- range .Array.Users }}
#    <li>
#        {{ .FirstName }}
#        {{ .LastName }}
#        {{ .Email }}
#    </li>
# {{- end }}
# </ul>
# Add your own Data arrays here:
[[Array.Header]]
    Name = "Firestatic Base Project"
    URL = "/"

[[Array.Header]]
    Name = "Contact"
    URL = "/contact"

[[Array.Footer]]
    Name = "Provider"
    URL = "/"
